# Generated by Django 3.2 on 2021-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210501_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_description',
            field=models.CharField(blank=True, default='', max_length=600, null=True),
        ),
    ]
