# Generated by Django 3.2 on 2021-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210501_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='more_description',
            field=models.CharField(default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
